#!/usr/bin/env python3
"""Generate a small synthetic cohort so the analysis stage is runnable offline.

    python demo/make_synthetic_cohort.py --out-dir demo/data

No patient data ships with this repository. This writes feature tables with the
same schema as stage 02 for a made-up cohort, with a planted effect: penumbra
that goes on to infarct is shifted away from salvaged penumbra, and infarcted
non-hypoperfused brain is shifted far from healthy contralateral brain. Running
the stage-03 scripts on it should therefore reproduce the *shape* of the
published result (Test 1 and Test 4 separate, Test 2 barely) on numbers that
mean nothing clinically.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

REGIONS = ["core_fi", "core_brain", "pen_fi", "pen_brain", "clb_brain", "nhb_fi"]

#: Per-class shift along a shared signal direction. Salvaged tissue sits near
#: healthy brain; infarcted tissue sits away from it.
SHIFT = {
    "clb_brain": 0.0,
    "pen_brain": 1.0,
    "core_brain": 2.0,
    "core_fi": 2.2,
    "pen_fi": 3.4,
    "nhb_fi": 5.0,
}
FE1_FEATURES = ["mean", "std", "skewness", "min", "max", "kurtosis"]
FE2_FEATURES = ["Imc1", "Imc2", "Correlation", "MCC"]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out-dir", default="demo/data")
    parser.add_argument("--patients", type=int, default=24)
    parser.add_argument("--slices", type=int, default=6)
    parser.add_argument("--dims", type=int, default=32, help="embedding dimensionality")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    patients = [f"sub-stroke_99_{i:03d}" for i in range(1, args.patients + 1)]
    direction = rng.normal(size=args.dims)
    direction /= np.linalg.norm(direction)

    slice_rows, hand_rows = [], []
    for pi, patient in enumerate(patients):
        patient_offset = rng.normal(scale=0.2, size=args.dims)
        for region in REGIONS:
            n_slices = args.slices if region in ("clb_brain", "pen_brain") else max(2, args.slices - 2)
            for z in range(n_slices):
                embedding = patient_offset + rng.normal(scale=0.4, size=args.dims)
                embedding += SHIFT[region] * direction
                slice_rows.append(
                    {"patient_id": patient, "slice": z, "region": region,
                     **{f"feat_{i}": v for i, v in enumerate(embedding)}}
                )
            centre = SHIFT[region]
            hand_rows.append(
                {
                    "patient_id": patient,
                    "region": region,
                    "n_voxels": int(rng.integers(500, 50_000)),
                    "cohort": "LVO" if pi % 2 == 0 else "Non-LVO",
                    **{f: float(centre + rng.normal(scale=0.6)) for f in FE1_FEATURES},
                    **{f: float(centre + rng.normal(scale=0.6)) for f in FE2_FEATURES},
                }
            )

    slice_df = pd.DataFrame(slice_rows)
    hand_df = pd.DataFrame(hand_rows)

    # FE3/FE4 style: slice-level embeddings. FE4 additionally carries one column
    # family per pooling operator, which is what the ablation switches between.
    slice_df.to_csv(out_dir / "fe3_slice_features.csv", index=False)
    pooled = slice_df[["patient_id", "slice", "region"]].copy()
    for i in range(args.dims):
        base = slice_df[f"feat_{i}"].to_numpy()
        # Each pooling operator gets its own jitter, so the ablation has three
        # genuinely different column families rather than affine copies.
        pooled[f"f{i}_mean"] = base + rng.normal(scale=0.10, size=base.size)
        pooled[f"f{i}_median"] = base + rng.normal(scale=0.12, size=base.size)
        pooled[f"f{i}_max"] = base * 1.05 + rng.normal(scale=0.20, size=base.size)
    pooled.to_csv(out_dir / "fe4_slice_features.csv", index=False)

    hand_df.to_csv(out_dir / "fe1_patient_features.csv", index=False)
    hand_df.to_csv(out_dir / "fe2_patient_features.csv", index=False)

    # Paths are written relative to the config file itself, so the config works
    # from any working directory.
    config = """# Auto-generated by demo/make_synthetic_cohort.py - synthetic data, not the paper's.
out_dir: results

features:
  fe1:
    sus: {path: fe1_patient_features.csv, level: patient}
  fe2:
    sus: {path: fe2_patient_features.csv, level: patient}
  fe3:
    sus: {path: fe3_slice_features.csv, level: slice, prefix: "feat_"}
  fe4:
    sus: {path: fe4_slice_features.csv, level: slice, suffix: "_max"}

fdr_scope:
  fe1: per_pair
  fe2: per_family
"""
    (out_dir / "config.yaml").write_text(config)

    print(f"wrote synthetic cohort to {out_dir}/")
    print(f"  {len(patients)} patients, {len(slice_df)} slice rows, {args.dims}-D embeddings")
    print(f"\nnext:\n  cd 03_analysis && python run_table3_region_pairs.py --config ../{out_dir}/config.yaml")


if __name__ == "__main__":
    main()
